name: Manual trigger sample

on:
  workflow_dispatch:
    inputs:
      exit_code:
        description: 'exit code'
        required: true
        default: '0'
    description: 'sample with input'

jobs:
  maual-trigger-sample:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: echo "Repo name is ${{ github.event.repository.name }}"
    - run: ./exit_with_args.bash "${{ github.event.inputs.exit_code }}"

