name: Manual trigger sample

on:
  workflow_dispatch:
    description: 'sample'

jobs:
  maual-trigger-sample:
    runs-on: ubuntu-latest

    steps:
    - name: Set versions
      run: echo "manual trigger sample"
